config/routes.rb
SampleApp::Application.routes.draw do
  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

  get 'pages/home'
  get 'pages/contact'
  get 'pages/about'
  get 'pages/help'

  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'
  match '/help' => 'pages#help'
  match '/signup' => 'users#new'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  default_scope :order => 'microposts.created_at DESC'

  validates :content, :presence => true,
                      :length => { :maximum => 140 }
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy

  validates :name, :presence => true, 
                   :length => { :maximum => 50 }
  validates :email, :presence => true, 
                    :format => { :with => /\A[\w.\-]+@[\w.\-]+\.\w+\z/ },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password

  def self.authenticate email, password
    user = self.find_by_email email
    user && user.has_password?(password) ? user : nil
  end

  def self.authenticate_with_salt id, cookie_salt
    user = User.find_by_id(id)
    user && user.salt == cookie_salt ? user : nil
  end

  def has_password? guess
    encrypted_password == encrypt(guess)
  end

  def feed
    # the ? notation helps avoid SQL injection
    # it ensures that variables are escaped
    # always always always escape your sql!
    Micropost.where('user_id = ?', id)
  end

  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt password
    end

    def encrypt string
      secure_hash "#{salt}--#{string}"
    end

    def secure_hash string
      Digest::SHA2.hexdigest string
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])

    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = current_user.feed.paginate(:page => params[:page])
      render 'pages/home'
    end
  end

  def destroy
    @micropost.destroy # @micropost is set in the authorized_user before filter
    redirect_to root_path, :flash => { :success => "Micropost deleted!" }
  end

  private
    def authorized_user
      @micropost = Micropost.find(params[:id])
      redirect_to root_path unless current_user?(@micropost.user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = 'Sign in'
  end

  def create
    user = User.authenticate(params[:session][:email], 
                             params[:session][:password])

    if user.nil?
      @title = "Sign in"
      flash.now[:error] = "Something went wrong!"
      render :new
    else
      sign_in user
      flash[:success] = "Welcome back!"
      redirect_to session[:return_to] || user
      session.delete(:return_to)
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [ :index, :edit, :update, :destroy ]
  before_filter :correct_user, :only => [ :edit, :update ]
  before_filter :admin_user, :only => [ :destroy ]

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => 1)
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = 'Sign up'
      flash.now[:error] = "Sorry, something went wrong!"
      render :new
    end
  end

  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = "You updated your profile successfully!"
      redirect_to @user
    else
      @title = "Edit user"
      flash.now[:error] = "Something went wrong!"
      render :edit # calls to render don't excecute the controller action!
    end
  end

  def destroy
    user_to_destroy = User.find(params[:id])

    if user_to_destroy == current_user
      flash[:error] = "You can't destroy your own admin account!"
    else
      flash[:success] = "User destroyed."
      user_to_destroy.destroy
    end

    redirect_to users_path
  end

  private
    def correct_user
      redirect_to root_path unless current_user?(User.find(params[:id]))
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in user
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    @current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user? user
    user == current_user
  end

  def signed_in?
    !!current_user
  end

  private
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def deny_access
      store_location
      redirect_to signin_path, :notice => "Please sign in to view this page."
    end

    def store_location
      session[:return_to] = request.path
    end

    def authenticate
      deny_access unless signed_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag user.email.downcase, :alt => user.name, 
                                            :class => 'gravatar',
                                            :gravatar => options
  end
end

app/views/layouts/_footer.haml
%footer
  %nav(class="round")
    %ul
      %li= link_to 'About', about_path
      %li= link_to 'Contact', contact_path
      %li= link_to 'News', 'http://news.railstutorial.org/'
      %li= link_to 'Rails Tutorial', 'http://railstutorial.org/'
      

app/views/layouts/_header.haml
%header
  = link_to logo, root_path
  %nav(class="round")
    %ul
      %li= link_to "Home", root_path
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Profile", user_path(current_user)
        %li= link_to "Users", users_path
        %li= link_to "Settings", edit_user_path(current_user)
        %li= link_to "Sign out", signout_path
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.haml
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print', :media => 'print'
/[if lt IE 9]
  %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")
/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie'
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title= title
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    .container
      = render 'layouts/header'
      %section(class="round")
        - flash.each do |key, value|
          %div(class="flash #{key}")
            = value
        = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/microposts/_micropost.haml
%tr
  %td(class="micropost")
    %span(class="content")= micropost.content
    %span(class="timestamp")
      Posted #{time_ago_in_words(micropost.created_at)} ago
  - if current_user?(micropost.user)
    %td
      = link_to 'delete', micropost, :method => :delete,
                                     :confirm => "Sure?",
                                     :title => micropost.content

app/views/pages/about.haml
%h1 Pages#about
%p Find me in app/views/pages/about.haml

app/views/pages/contact.haml
%h1 Contact
:markdown
  Contact Ruby on Rails Tutorial about the sample app at the
  [feedback page](http://railstutorial.org/). Also, note that when you insert
  a :markdown filter, haml will automatically wrap that content in a paragraph
  tag!

app/views/pages/help.haml
%h1 Pages#help
%p Find me in app/views/pages/help.haml

app/views/pages/home.haml
- if signed_in?
  %table(class="front" summary="For signed-in users")
    %tr
      %td(class="main")
        %h1(class="micropost")
          What's up?
        = render 'shared/micropost_form'
        = render 'shared/feed'
      %td(class="sidebar round")
        = render 'shared/user_info'
- else
  %h1 Sample App
  %p
    This is the home page for the
    %a(href="http://railstutorial.org/") Ruby on Rails Tutorial
    sample app.

  = link_to "Sign up now!", signup_path, :class => "signup_button round"

app/views/shared/_error_messages.haml
- if object.errors.any?
  #error_explanation
    %h2 
      #{pluralize(object.errors.count, "error")} prevented 
      this #{object.class.to_s.underscore.humanize.downcase} from being saved:
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.haml
- if @feed_items.any?
  %table(class="microposts" summary="Status feed")
    = render :partial => 'shared/feed_item', :collection => @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.haml
%tr
  %td(class="gravatar")
    = link_to gravatar_for(feed_item.user), feed_item.user
  %td(class="micropost")
    %span(class="user")
      = link_to feed_item.user.name, feed_item.user
    %span(class="content")
      = feed_item.content
    %span(class="timestamp")
      Posted #{time_ago_in_words(feed_item.created_at)} ago.
  -if current_user?(feed_item.user)
    %td
      = link_to "delete", feed_item, :method => :delete,
                                     :confirm => "Sure?",
                                     :title => feed_item.content

app/views/shared/_micropost_form.haml
= form_for @micropost do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.text_area :content
  .actions
    = f.submit "Post!"

app/views/shared/_user_info.haml
.user_info
  %a(href="#{user_path(current_user)}")
    = gravatar_for current_user, :size => 30
    %span(class="user_name")
      = current_user.name
    %span(class="microposts")
      = pluralize(current_user.microposts.count, "micropost")

app/views/users/_fields.haml
= render 'shared/error_messages', :object => @user
.field
  = f.label :name
  %br
  = f.text_field :name
.field
  = f.label :email
  %br
  = f.text_field :email
.field
  = f.label :password
  %br
  = f.password_field :password
.field
  = f.label :password_confirmation, "Confirmation"
  %br
  = f.password_field :password_confirmation

app/views/users/_user.haml
%li
  = gravatar_for user, :size => 30
  = link_to user.name, user
  - if current_user.admin?
    |
    = link_to "delete", user, :method => :delete,
      :confirm => "Are you sure you want to delete this user?",
      :title => "Delete #{user.name}"

app/views/users/edit.haml
%h1 Edit user

= form_for @user do |f|
  = render 'shared/error_messages', :object => f.object
  = render 'fields', :f => f
  .actions
    = f.submit "Update"
 
= gravatar_for @user
%a(href="http://gravatar.com/emails" target="_blank") change

app/views/users/index.haml
%h1 All users

= will_paginate

%ul(class="users")
  = render @users 

= will_paginate

app/views/users/new.haml
%h1 Sign up

= form_for @user do |f|
  = render 'shared/error_messages', :object => f.object
  = render 'fields', :f => f
  .actions
    = f.submit "Sign up!"

%p 
  Already have an account?
  = link_to 'Sign in!', signin_path

app/views/users/show.haml
#notice

%table(class="profile" summary="Profile information")
  %tr
    %td(class="main")
      %h1
        = gravatar_for @user
        = @user.name
      - if @user.microposts.any?
        %table(class="microposts" summary="User microposts")
          = render @microposts
        = will_paginate(@microposts)
    %td(class="sidebar round")
      %strong Name
      = @user.name
      %br
      %strong URL
      = link_to user_path(@user)
      %strong Microposts
      = @user.microposts.count